[package]
name = "certgen-rs"
version = "0.1.0"
edition = "2021"
authors = ["Rafael Escrich <rafaelescrich@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rui = "0.6.1"
openssl = "0.10"